import { Respira } from "./images";

export const products = [
  {
    id: 1,
    name: "Syltherine",
    category: "Stylish cafe chair",
    image: Respira,
    price: 2500000,
    oldPrice: 3500000,
  },
  {
    id: 2,
    name: "Leviosa",
    category: "Stylish cafe chair",
    image: Respira,
    price: 2500000,
  },
  {
    id: 3,
    name: "Lolito",
    category: "Luxury big sofa",
    image: Respira,
    price: 7000000,
    oldPrice: 14000000,
  },
  {
    id: 4,
    name: "Respira",
    category: "Outdoor bar table and stool",
    image: Respira,
    price: 500000,
    isNew: true,
  },
  {
    id: 5,
    name: "Grifo",
    category: "Night lamp",
    image: Respira,
    price: 1500000,
  },
  {
    id: 6,
    name: "Muggo",
    category: "Small mug",
    image: Respira,
    price: 150000,
    isNew: true,
  },
  {
    id: 7,
    name: "Pingky",
    category: "Cute bed set",
    image: Respira,
    price: 7000000,
    oldPrice: 14000000,
  },
  {
    id: 8,
    name: "Potty",
    category: "Minimalist flower pot",
    image: Respira,
    price: 500000,
    isNew: true,
  },
];
